### ISSUE TITLE
Возможная уязвимость

### ISSUE THREAD

**Issue by RedCrabVb** [voidTestUsername/TeleNotesBot#3]
Уверен, что такая защита сработает? Я нет, глянь в эту сторону: https://stackoverflow.com/questions/45128902/psycopg2-and-sql-injection-security
https://github.com/voidTestUsername/TeleNotesBot/blob/9824bed21b3350c0f20abf6ce9f3abf15f8392f7/TeleNotesBot.py#L10

**Comment by voidTestUsername** [comment]
Старую защиту убрал, сделал как в примере

**Comment by RedCrabVb** [comment]
> Старую защиту убрал, сделал как в примере

В какой ветке?

**Comment by voidTestUsername** [comment]
> 

issue-3
